AllCops:
  TargetRubyVersion: 2.5.6

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/BlockLength:
  Max: 32

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys
